import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-gray-900 flex flex-col items-center">
          <div className="w-full max-w-xl">
            <Link href="/">
              <h1 className="border border-gray-800 border-t-0 px-4 text-xl font-bold py-6">
                Home
              </h1>
            </Link>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
