import Link from "next/link";
import "./globals.css";
import Logout from "./logout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-gray-900 flex flex-col">
          <div className="w-full max-w-xl flex flex-col flex-1 mx-auto">
            <Link
              href="/"
              className="flex border border-gray-800 border-t-0 px-4 py-6 items-center justify-between"
            >
              <h1 className=" text-xl font-bold">Home</h1>
              <Logout />
            </Link>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
